name: animal_classification
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: 0.17.0
  flutter_slidable: ^0.6.0
  cupertino_icons: ^1.0.2
  sqflite: ^1.2.0
  scoped_model: ^1.1.0
  path_provider:
  shared_preferences: ^2.0.15
  email_validator: ^2.0.1

  #firebase
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1


  # Main packages for our app
  tflite: ^1.1.2
  image_picker: ^0.8.3+2

  # For app logo and Splash Screen
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1


flutter_native_splash:
  color: "#E0F3FD"
  image: assets/icons/logo.jpg
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
